"""Arch-v2 dual-perspective HalfKP features (mirror of the Rust encoder).

Perspective-relative shared feature transformer per the standard NNUE design:
from each side's perspective the board is oriented so that side plays "up"
(black flips square indices with ^56) and piece colors are expressed as own
(planes 0-4, order P N B R Q) / opponent (planes 5-9). Side-to-move is
expressed by concatenation order at training/eval time, not by the index.

Must stay byte-identical in behavior to PieBot/src/eval/nnue/features.rs
(dp_idx_for / dp_active_indices); tests/nnue_arch_v2.rs asserts this against
the committed fixture generated by `python -m training.nnue.features_v2`.
"""

from __future__ import annotations

from typing import List, Tuple

PER_PERSPECTIVE_DIM = 64 * 10 * 64  # 40,960
FEATURE_SET_V2 = "halfkp-dp-screlu-v1"
PIECE_PLANES = "PNBRQ"


def _parse_board(fen: str) -> Tuple[List[Tuple[str, int]], int, int, bool]:
    parts = fen.split()
    board_part = parts[0]
    stm_white = len(parts) < 2 or parts[1] == "w"
    ranks = board_part.split("/")
    if len(ranks) != 8:
        raise ValueError(f"invalid FEN board part: {board_part}")
    pieces: List[Tuple[str, int]] = []
    white_king = black_king = None
    for fen_rank, rank_str in enumerate(ranks):
        rank_idx = 7 - fen_rank
        file_idx = 0
        for ch in rank_str:
            if ch.isdigit():
                file_idx += int(ch)
                continue
            sq = rank_idx * 8 + file_idx
            pieces.append((ch, sq))
            if ch == "K":
                white_king = sq
            elif ch == "k":
                black_king = sq
            file_idx += 1
    if white_king is None or black_king is None:
        raise ValueError(f"FEN missing a king: {fen}")
    return pieces, white_king, black_king, stm_white


def dp_idx_for(persp_white: bool, king_sq: int, piece_is_white: bool,
               piece_plane: int, sq: int) -> int:
    flip = 0 if persp_white else 56
    own = piece_is_white == persp_white
    colored = piece_plane if own else 5 + piece_plane
    return (((king_sq ^ flip) * 10 + colored) * 64) + (sq ^ flip)


def active_indices(fen: str) -> Tuple[List[int], List[int], bool]:
    """Return (white_perspective, black_perspective, stm_is_white).

    Index order within each perspective matches the Rust extractor: white
    pieces first then black pieces, each in plane order P N B R Q, squares in
    board-scan order as produced by cozy-chess bitboard iteration (ascending
    square index).
    """
    pieces, wk, bk, stm_white = _parse_board(fen)
    out: List[List[int]] = []
    for persp_white, ksq in ((True, wk), (False, bk)):
        idxs: List[int] = []
        for want_white in (True, False):
            for plane, plane_ch in enumerate(PIECE_PLANES):
                selected = [
                    (ch, sq) for ch, sq in pieces
                    if ch.upper() == plane_ch and ch.isupper() == want_white
                ]
                for _ch, sq in sorted(selected, key=lambda t: t[1]):
                    idxs.append(dp_idx_for(persp_white, ksq, want_white, plane, sq))
        out.append(idxs)
    return out[0], out[1], stm_white


def stm_ordered(fen: str) -> Tuple[List[int], List[int]]:
    """(stm_indices, opponent_indices) — the training-time input order."""
    white_p, black_p, stm_white = active_indices(fen)
    return (white_p, black_p) if stm_white else (black_p, white_p)


if __name__ == "__main__":
    import json
    import sys

    fens = [
        "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R b KQkq - 5 5",
        "r2q1rk1/1b2bppp/p2ppn2/1p6/3NP3/1BN5/PPP2PPP/R2Q1RK1 w - - 0 12",
        "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1",
        "4k3/8/8/8/8/7r/4P3/4K3 b - - 0 1",
        "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1",
    ]
    rows = []
    for fen in fens:
        white_p, black_p, stm_white = active_indices(fen)
        rows.append({
            "fen": fen,
            "white_perspective": sorted(white_p),
            "black_perspective": sorted(black_p),
            "stm_is_white": stm_white,
        })
    json.dump({"per_perspective_dim": PER_PERSPECTIVE_DIM, "positions": rows},
              sys.stdout, indent=1)
    sys.stdout.write("\n")
